[tool.poetry]
name = "{{ cookiecutter.repo_name }}-ansible"
version = "1.0.0"
description = "Ansible scripts for {{ cookiecutter.project_title }} deployment"
authors = ["Thorgate <hi@thorgate.eu>"]

[tool.poetry.dependencies]
python = "^3.6"
ansible = "^2.9"
jinja2 = "^2.10"
docker-compose = "^1.25"
cryptography = "^2.8"
yq = "^2.12.2"
jq = "^1.2.1"

[tool.poetry.dev-dependencies]
PyYAML = "^5.3"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
